#include <iostream>
int main(){
   int a,b;
   std::cout<<"Enter a :";
   std::cin>>a;
   std::cout<<"Enter b :";
   std::cin>>b;
   switch(a){
      case 1 :
      std::cout<<"one";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"two";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"three";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"four";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"five";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"six";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"seven";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"eight";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"nine";
      a++;
      if(a>b){
         break;
      }
      for(int a=0;a<=b;a++){
         if(a%b==0){
            std::cout<<"even";
         }
         else{
            std::cout<<"odd";
         }
      }
      case 2 :
      std::cout<<"two";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"three";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"four";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"five";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"six";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"seven";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"eight";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"nine";
      a++;
      if(a>b){
         break;
      }
      for(int a=0;a<=b;a++){
         if(a%b==0){
            std::cout<<"even";
         }
         else{
            std::cout<<"odd";
         }
      }
      case 3 :
      std::cout<<"three";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"four";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"five";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"six";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"seven";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"eight";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"nine";
      a++;
      if(a>b){
         break;
      }
      for(int a=0;a<=b;a++){
         if(a%b==0){
            std::cout<<"even";
         }
         else{
            std::cout<<"odd";
         }
      }
      case 4 :
      std::cout<<"four";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"five";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"six";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"seven";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"eight";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"nine";
      a++;
      if(a>b){
         break;
      }
      for(int a=0;a<=b;a++){
         if(a%b==0){
            std::cout<<"even";
         }
         else{
            std::cout<<"odd";
         }
      }
      case 5 :
      std::cout<<"five";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"six";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"seven";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"eight";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"nine";
      a++;
      if(a>b){
         break;
      }
      for(int a=0;a<=b;a++){
         if(a%b==0){
            std::cout<<"even";
         }
         else{
            std::cout<<"odd";
         }
      }
      case 6 :
      std::cout<<"six";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"seven";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"eight";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"nine";
      a++;
      if(a>b){
         break;
      }
      for(int a=0;a<=b;a++){
         if(a%b==0){
            std::cout<<"even";
         }
         else{
            std::cout<<"odd";
         }
      }
      case 7 :
      std::cout<<"seven";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"eight";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"nine";
      a++;
      if(a>b){
         break;
      }
      for(int a=0;a<=b;a++){
         if(a%b==0){
            std::cout<<"even";
         }
         else{
            std::cout<<"odd";
         }
      }
      case 8 :
      std::cout<<"eight";
      a++;
      if(a>b){
         break;
      }
      std::cout<<"nine";
      a++;
      if(a>b){
         break;
      }
      for(int a=0;a<=b;a++){
         if(a%b==0){
            std::cout<<"even";
         }
         else if(a%b==1){
            std::cout<<"odd";
         }
      }
      case 9 :
      std::cout<<"nine";
      a++;
      if(a>b){
         break;
      }
      for(int a=0;a<=b;a++){
         if(a%b==0){
            std::cout<<"even";
         }
         else{
            std::cout<<"odd";
         }
      }
   }
   return 0;
}